### PR TITLE
Fix Typescript definitions to allow for props forwarded to SVG element: style, onClick, etc.

### LINKED ISSUE #48: Allow props forwarded to the svg component in typescript
Since we can forward props to the `svg` element (eg `style`), this should be reflected in the props type definition `MdiReactIconProps`.

To reproduce:
```javascript
import CloseIcon from 'mdi-react/CloseIcon'

const MyComponent: React.FC<{}> = () => {
  return <CloseIcon style={{marginLeft: 5}} />
}
```

This raises a type-script error 
```
error TS2322: Type '{ style: { marginLeft: number; }; }' is not assignable to type 'IntrinsicAttributes & MdiReactIconProps & { children?: ReactNode; }'.
  Property 'style' does not exist on type 'IntrinsicAttributes & MdiReactIconProps & { children?: ReactNode; }'.
```

### PR DESCRIPTION
**Pull request by pcorpet**
Fixes #48.

---
This change is [Reviewable](https://reviewable.io/reviews/levrik/mdi-react/50)

### CODE REVIEW

**Comment by levrik** [comment]
Awesome. Thanks!
As soon as I have time I will take a look at it. Probably next week.

**Comment by levrik** [comment]
@pcorpet I don't quite understand the combination of `Pick` and `Exclude`. Could you elaborate on that?

**Comment by pcorpet** [comment]
Pick + Exclude is the equivalent of Omit before Omit was invented:
```js
Pick<SVGProps, Exclude<keyof SVGProps, ReservedProps>>
```
is the equivalent (inTypescript 3.5) of
```js
Omit<SVGProps, ReservedProps>
```
See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-5.html#the-omit-helper-type

Which is taking the SVGProps interface but removing the fields mentionned in ReservedProps (size, width, height, fill, viewBox). I'm omitting width & height as you should not set them. I'm omitting size because we're changing its type, and finally omitting fill & viewBox because if you set them on the icon externally those properties are overriden by the implementation.

The exact detail is: Pick<A, Exclude<B, C>>
Pick the fields of A that are in B but not in C, which in my case: pick the fields of SVGProps that are in (keyof SVGProps) but are not in ReservedProps.

**Comment by pcorpet** [comment]
@levrik A friendly ping.

**Comment by levrik** [comment]
@pcorpet Hey. Sorry. Got it now. I'm gonna merge and release it the coming weekend.

File: scripts/generate-react.js [hunk 1]
```diff
@@ -17,12 +17,15 @@ export default ${component.name};
 
 declare const ${component.name}: MdiReactIconComponentType;
 export default ${component.name};
-`, () => `import { ComponentType } from 'react';
+`, () => `import { ComponentType, HTMLProps } from 'react';
 
-export interface MdiReactIconProps {
+type SVGProps = HTMLProps<SVGElement>
```
Comment (levrik) [inline scripts/generate-react.js]: Could we use `SVGProps<SVGSVGElement>` here instead of `HTMLProps<SVGElement>`.

File: scripts/generate-preact.js [hunk 2]
```diff
@@ -17,9 +17,13 @@ export default ${component.name};
...
 export default ${component.name};
-`, () => `import { FunctionalComponent } from 'preact';
+`, () => `import { FunctionalComponent, HTMLProps } from 'preact';
 
-export interface MdiReactIconProps {
+type SVGProps = HTMLProps<SVGElement>
+
+type ReservedProps = 'size' | 'width' | 'height' | 'fill' | 'viewBox'
+
+export interface MdiReactIconProps extends Pick<SVGProps, Exclude<keyof SVGProps, ReservedProps>> {
```
Comment (levrik) [inline scripts/generate-preact.js]: I just did some research and found out that basically there are no typings for SVG elements in the current stable release of Preact. This will improve with Preact 10.x which is still in beta. Please just revert the changes for the Preact generator since they break the current typings.

Comment (pcorpet) [reply scripts/generate-preact.js]: Wow good catch. Reverted.

File: scripts/generate-react.js (hunk 1 above)
Comment (pcorpet) [reply scripts/generate-react.js]: Done. thanks.

**Comment by davwheat** [comment]
Any update on when this will be merged? I really want to use this :)

File: scripts/generate-preact.js [hunk 3]
```diff
@@ -19,6 +19,8 @@ declare const ${component.name}: MdiReactIconComponentType;
 export default ${component.name};
 `, () => `import { FunctionalComponent } from 'preact';
 
+# TODO(pcorpet): Extends SVGProps when it exists in PReact.
```
Comment (levrik) [inline scripts/generate-preact.js]:
```suggestion
// TODO(pcorpet): Extends SVGProps when it exists in Preact
```

File: scripts/generate-react.js [hunk 4]
```diff
@@ -17,12 +17,15 @@ export default React.memo ? React.memo(${component.name}) : ${component.name};
 
 declare const ${component.name}: MdiReactIconComponentType;
 export default ${component.name};
-`, () => `import { ComponentType } from 'react';
+`, () => `import { ComponentType, SVGProps } from 'react';
 
-export interface MdiReactIconProps {
+type AllSVGProps = SVGProps<SVGSVGElement>
+
+type ReservedProps = 'size' | 'width' | 'height' | 'fill' | 'viewBox'
```
Comment (levrik) [inline scripts/generate-react.js]:
```suggestion
type ReservedProps = 'color' | 'size' | 'width' | 'height' | 'fill' | 'viewBox'
```
To avoid type merging with our own definition. `color` is already defined as `string` on `SVGProps`.

File: scripts/generate-preact.js (hunk 3 above)
Comment (pcorpet) [reply scripts/generate-preact.js]: Thanks. Sorry for that.

File: scripts/generate-react.js (hunk 4 above)
Comment (pcorpet) [reply scripts/generate-react.js]: Integrated.

**Comment by levrik** [comment]
Sorry for the delay again. I'll merge and release this coming weekend.

**Comment by pcorpet** [comment]
It looks like there was a release this weekend, but this PR got forgotten :-(

**Comment by levrik** [comment]
@pcorpet Sorry for another week of delay. The release last weekend was automated due to updated upstream `mdi`.

**Comment by levrik** [comment]
Released in `6.4.0`.
